language: ruby
rvm:
  - 2.2.2
  - 2.3.4
  - 2.4.1

gemfile:
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head

sudo: false
cache: bundler
